ITEM.name = "M1918 BAR"
ITEM.desc = ""
ITEM.model = "models/weapons/w_m1918_bar.mdl"
ITEM.class = "tfa_m1918bar"
ITEM.weaponCategory = "primary"
ITEM.uniqueID = "m1918bar"
ITEM.permit = "admin"
ITEM.price = 100
ITEM.width = 4
ITEM.height = 1
ITEM.flag = "Y"