ITEM.name = "Box of Bandages"
ITEM.model = "models/items/healthkit.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.healAmount = 15
ITEM.healSeconds = 3
ITEM.price = 0
ITEM.desc = "A small box filled with bandages."
ITEM.uniqueID = "medical_bandages"
ITEM.flag = "v"
ITEM.container = "j_empty_bandage"
