ITEM.name = "Military Clothing Permit"
ITEM.uniqueID = "permit_mcp"
ITEM.model = "models/props_c17/paper01.mdl"
ITEM.category = "Permits"
ITEM.desc = "A permit that allows one to order Military Clothing."