ITEM.name = "Food Permit"
ITEM.uniqueID = "permit_food"
ITEM.model = "models/props_c17/paper01.mdl"
ITEM.category = "Permits"
ITEM.desc = "A permit that allows one to order various types of food."