ITEM.name = "Militsiya Permit"
ITEM.uniqueID = "permit_milit"
ITEM.model = "models/props_c17/paper01.mdl"
ITEM.category = "Permits"
ITEM.desc = "A permit that allows one to order Militsiya Equipment."